name: flutter_appmobile
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_lints: ^2.0.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  google_maps_flutter: ^2.1.1

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  go_router: ^14.6.2
  html: ^0.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
